In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix

ImportError: DLL load failed while importing base: %1 is not a valid Win32 application.

In [17]:
df = pd.read_excel("monkeypox.xlsx")
df.head()
# df.shape

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  Oral Lesions  \
0                 1            0            1              1             1   
1                 3            1            0              1             1   
2                 3            0            1              1             0   
3                 1            1            0              0             0   
4                 2            1            1              1             0   

   Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                0                1              0   
1                0                0              1   
2                0                0              1   
3                1                1              1   
4                0                1              1   

   Sexually Transmitted Infection  MonkeyPox  
0                               0          0  
1                               0          1  
2                               0          1  
3                               0          1  
4                               0          1

In [1]:
# import matplotlib.pyplot as plt
# import pandas as pd
# import seaborn as sns

# #visualisasi matrix

# # heatmp
# df = df.corr()       #hubungan antar var, korelasi
# # sns.heatmap(df)
# sns.heatmap(df,  annot=False, cmap="Blues")    #annot memberikan nilai pada gambarnya, c map=mengubah warna tema
# plt.show()

# print(df.head())

In [18]:
# memisahkan data dari class
X = df.drop(columns='MonkeyPox', axis=1)
Y = df['MonkeyPox']

In [20]:
# normalisation: merubah ke rentang tertentu
# why? mengurangi kompleksitas data, mrnghindari overfitting, mempercepat proses pelatihan, menormalkan residu
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
standarized_data = scaler.fit_transform(X)
standarized_data

array([[0.        , 0.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.66666667, 0.        , 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.66666667, 0.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.66666667, 0.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [19]:
import tensorflow as tf
# no module

ModuleNotFoundError: No module named 'tensorflow'

In [21]:
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [22]:
standarized_data = scaler.transform(X)
standarized_data

array([[-1.33471619, -0.98265048,  1.03823026, ...,  1.        ,
        -0.94880848, -1.02532046],
       [ 0.43311982,  1.01765584, -0.96317747, ..., -1.        ,
         1.05395348, -1.02532046],
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
         1.05395348, -1.02532046],
       ...,
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
         1.05395348,  0.97530483],
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
        -0.94880848,  0.97530483],
       [-1.33471619,  1.01765584, -0.96317747, ..., -1.        ,
         1.05395348, -1.02532046]])

In [23]:
X = standarized_data
Y = df['MonkeyPox']

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2, stratify=Y, random_state=42)
# random 42, k3 = 58%, k5= 56, k7 = 51, k8=52, k9= 

In [25]:
X.shape, X_train.shape, X_test.shape

((800, 9), (640, 9), (160, 9))

In [26]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=4)

In [22]:
# from sklearn.model_selection import StratifiedKFold, cross_val_score
# sk_folds = StratifiedKFold(n_splits = 5)

# scores = cross_val_score(knn, X, Y, cv = sk_folds )
# print(scores)
# print(scores.mean())
# print(len(scores))

In [27]:
y_predict = knn.predict(X_test)
print(classification_report(Y_test, y_predict))

              precision    recall  f1-score   support

           0       0.58      0.76      0.66        80
           1       0.65      0.45      0.53        80

    accuracy                           0.61       160
   macro avg       0.62      0.61      0.60       160
weighted avg       0.62      0.61      0.60       160



D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [28]:
# accuracy manual
cm = confusion_matrix(Y_test, y_predict)
cm

array([[61, 19],
       [44, 36]], dtype=int64)

In [29]:
X_train_prediction = knn.predict(X_train)
training_data_accuration = accuracy_score(X_train_prediction, Y_train)
training_data_accuration # 0.71%(n=5), 0.77%(n=3)

D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.6953125

In [30]:
X_test_prediction = knn.predict(X_test)
training_data_accuration2 = accuracy_score(X_test_prediction, Y_test)
training_data_accuration2 # 0.54%(n=5), 0.56%(n=3)

D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.60625

In [31]:
import numpy as np
from sklearn.preprocessing import StandardScaler

input_data = (0,0,0,1,1,1,0,1,0)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)
std_data = scaler.transform(input_data_reshape)
# std_data
prediction = knn.predict(std_data)
prediction
# hasil sudah benar

D:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0], dtype=int64)

In [128]:
import pickle
filename = 'monkeypox_model5.sav'
pickle.dump(knn, open(filename, 'wb'))