In [3]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix

In [4]:
df = pd.read_excel('monkeypox.xlsx')
df.head()

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  Oral Lesions  \
0                 1            0            1              1             1   
1                 3            1            0              1             1   
2                 3            0            1              1             0   
3                 1            1            0              0             0   
4                 2            1            1              1             0   

   Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                0                1              0   
1                0                0              1   
2                0                0              1   
3                1                1              1   
4                0                1              1   

   Sexually Transmitted Infection  MonkeyPox  
0                               0          0  
1                               0          1  
2                               0          1  
3                               0          1  
4                               0          1

In [5]:
# memisahkan data training dan testing
X = df.drop(columns='MonkeyPox', axis=1)
Y = df['MonkeyPox']

In [6]:
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [7]:
standarized_data = scaler.transform(X)
standarized_data

array([[-1.33471619, -0.98265048,  1.03823026, ...,  1.        ,
        -0.94880848, -1.02532046],
       [ 0.43311982,  1.01765584, -0.96317747, ..., -1.        ,
         1.05395348, -1.02532046],
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
         1.05395348, -1.02532046],
       ...,
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
         1.05395348,  0.97530483],
       [ 0.43311982, -0.98265048,  1.03823026, ..., -1.        ,
        -0.94880848,  0.97530483],
       [-1.33471619,  1.01765584, -0.96317747, ..., -1.        ,
         1.05395348, -1.02532046]])

In [8]:
X = standarized_data
Y = df['MonkeyPox']

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.4, stratify=Y, random_state=2)

In [10]:
X.shape, X_train.shape, X_test.shape

((800, 9), (480, 9), (320, 9))

In [11]:
# permodelan naive bayes
clf = GaussianNB()
clf.fit(X_train, Y_train)

GaussianNB()

In [12]:
y_predict = clf.predict(X_test)
print(classification_report(Y_test, y_predict))

              precision    recall  f1-score   support

           0       0.57      0.56      0.57       160
           1       0.57      0.57      0.57       160

    accuracy                           0.57       320
   macro avg       0.57      0.57      0.57       320
weighted avg       0.57      0.57      0.57       320



In [14]:
# accuracy manual
cm = confusion_matrix(Y_test, y_predict)
cm

array([[90, 70],
       [68, 92]], dtype=int64)

In [38]:
X_train_prediction = clf.predict(X_train)
training_data_accuration = accuracy_score(X_train_prediction, Y_train)
training_data_accuration # 0.60%

0.6083333333333333

In [39]:
X_test_prediction = clf.predict(X_test)
training_data_accuration2 = accuracy_score(X_test_prediction, Y_test)
training_data_accuration2 # 0.56%

0.56875

In [40]:
import numpy as np
from sklearn.preprocessing import StandardScaler

input_data = (1,0,1,0,0,0,0,1,1)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)
std_data = scaler.transform(input_data_reshape)
# std_data
prediction = clf.predict(std_data)
prediction
# hasil sudah benar

D:\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0], dtype=int64)